version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - spark-streaming
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - spark-streaming
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  pyspark:
    image: 'jupyter/pyspark-notebook'
    networks:
      - spark-streaming
    ports:
      - '8888:8888'
    volumes:
      - 'C:\Users\valdi\Documents\Spark\TrabalhoFinal:/home/jovyan/work'
    depends_on:
      - kafka

networks: 
  spark-streaming:
    driver: bridge